version: '3'
services:
  node1:
    container_name: raft-container-node-1
    image: raft-container-node:1
    build: .
    environment:
      - NODE_ID=1
      - PEERS=node2:5000,node3:5000
    ports:
      - "6500:5000"
    networks:
      - raft-network
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./disk:/app/disk 
      - ./logs:/app/logs

  node2:
    container_name: raft-container-node-2
    image: raft-container-node:2
    build: .
    environment:
      - NODE_ID=2
      - PEERS=node1:5000,node3:5000
    ports:
      - "6501:5000"
    networks:
      - raft-network
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./disk:/app/disk
      - ./logs:/app/logs

  node3:
    container_name: raft-container-node-3
    image: raft-container-node:3
    build: .
    environment:
      - NODE_ID=3
      - PEERS=node1:5000,node2:5000
    ports:
      - "6502:5000"
    networks:
      - raft-network
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./disk:/app/disk
      - ./logs:/app/logs
      
networks:
  raft-network:
    driver: bridge